### ISSUE TITLE
`node-gyp rebuild` fails on OS X 10.10.3

### ISSUE THREAD

**Issue by njurgens** [TritonDataCenter/node-uname#3]
```
> uname@0.0.2 install /private/tmp/node_modules/uname
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/uname.o
../uname.cc:15:32: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> call_uname(const Arguments& args)
                               ^~~~~~~~~
                               v8::internal::Arguments
/Users/USER/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../uname.cc:17:14: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/USER/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../uname.cc:22:33: error: too few arguments to function call, single argument 'isolate' was not specified
        Local<Object> rv = Object::New();
                           ~~~~~~~~~~~ ^
/Users/USER/.node-gyp/0.12.2/deps/v8/include/v8.h:2388:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
../uname.cc:24:18: error: no member named 'New' in 'v8::String'
        rv->Set(String::New("sysname"), String::New(uts.sysname));
                ~~~~~~~~^
../uname.cc:24:42: error: no member named 'New' in 'v8::String'
        rv->Set(String::New("sysname"), String::New(uts.sysname));
                                        ~~~~~~~~^
../uname.cc:25:18: error: no member named 'New' in 'v8::String'
        rv->Set(String::New("nodename"), String::New(uts.nodename));
                ~~~~~~~~^
../uname.cc:25:43: error: no member named 'New' in 'v8::String'
        rv->Set(String::New("nodename"), String::New(uts.nodename));
                                         ~~~~~~~~^
../uname.cc:26:18: error: no member named 'New' in 'v8::String'
        rv->Set(String::New("release"), String::New(uts.release));
                ~~~~~~~~^
../uname.cc:26:42: error: no member named 'New' in 'v8::String'
        rv->Set(String::New("release"), String::New(uts.release));
                                        ~~~~~~~~^
../uname.cc:27:18: error: no member named 'New' in 'v8::String'
        rv->Set(String::New("version"), String::New(uts.version));
                ~~~~~~~~^
../uname.cc:27:42: error: no member named 'New' in 'v8::String'
        rv->Set(String::New("version"), String::New(uts.version));
                                        ~~~~~~~~^
../uname.cc:28:18: error: no member named 'New' in 'v8::String'
        rv->Set(String::New("machine"), String::New(uts.machine));
                ~~~~~~~~^
../uname.cc:28:42: error: no member named 'New' in 'v8::String'
        rv->Set(String::New("machine"), String::New(uts.machine));
                                        ~~~~~~~~^
../uname.cc:36:14: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/USER/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../uname.cc:37:56: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)'
        Local<FunctionTemplate> templ = FunctionTemplate::New(call_uname);
                                                              ^~~~~~~~~~
/Users/USER/.node-gyp/0.12.2/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../uname.cc:39:22: error: no member named 'NewSymbol' in 'v8::String'
        target->Set(String::NewSymbol("uname"), templ->GetFunction());
                    ~~~~~~~~^
16 errors generated.
make: *** [Release/obj.target/binding/uname.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/node_modules/uname
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "uname"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! uname@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uname@0.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the uname package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls uname
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

**Comment by davepacheco** [comment]
node-uname has not been updated for recent versions of Node.  That's because it's largely obviated by functionality provide by Node itself.  Specifically, Node reports:
- "sysname" as os.type()
- "release" as os.release()
- "nodename" as os.hostname(),
- "machine" is related to process.arch

I don't see an analog for "version", though.

**Comment by Efreak** [comment]
Version is exactly what I need 😦
